"""Generate quizzes/STATUS.md: a log of which course modules have practice-quiz
questions, when those questions were last updated, and whether the module's
instruction notebooks have changed since (so the questions may be stale).

Staleness is derived from git commit dates:
  - quiz updated   = last commit that touched quizzes/<module>.md
  - module updated = most recent commit among the module's INSTRUCTION
                     notebooks (NN_M_*.ipynb), excluding *_Exercises* and any
                     *_practice_quiz* notebooks (those don't drive quiz content)
A quiz is STALE if its module was updated more recently than the quiz itself.

Run this after committing quiz/notebook changes, so the git dates are accurate:

    python quiz_site/quiz_status.py

It overwrites quizzes/STATUS.md. Do not hand-edit that file.

With --check it writes nothing and instead exits non-zero if any module is
stale or missing questions. CI runs this (as a warning, not a hard failure)
so a module going stale is visible without anyone remembering to look. Note
that staleness compares commit dates, so --check is only meaningful on a
full clone (fetch-depth: 0 in Actions).
"""
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
QUIZZES = REPO / "quizzes"

MODULE_DIR_RE = re.compile(r"^\d\d_")


def git_last_date(paths) -> str | None:
    """Most recent committer date (YYYY-MM-DD) across the given paths, or None
    if git knows nothing about them (untracked / never committed)."""
    paths = [str(p) for p in paths if Path(p).exists()]
    if not paths:
        return None
    out = subprocess.run(
        ["git", "-C", str(REPO), "log", "-1", "--format=%cs", "--", *paths],
        capture_output=True, text=True,
    ).stdout.strip()
    return out or None


def instruction_notebooks(module_dir: Path) -> list[Path]:
    """Concept/instruction notebooks only — exclude exercises and quiz nbs."""
    return sorted(
        nb for nb in module_dir.glob("*.ipynb")
        if "exercises" not in nb.name.lower()
        and "practice_quiz" not in nb.name.lower()
    )


def quiz_stats(md_path: Path) -> tuple[int, int]:
    """(sections, questions) in a quiz Markdown file."""
    if not md_path.exists():
        return (0, 0)
    text = md_path.read_text()
    sections = len(re.findall(r"^## ", text, re.MULTILINE))
    questions = len(re.findall(r"^### ", text, re.MULTILINE))
    return (sections, questions)


def main(check_only: bool = False):
    modules = sorted(
        d for d in REPO.iterdir()
        if d.is_dir() and MODULE_DIR_RE.match(d.name)
    )

    rows = []
    needs, stale, ok = 0, 0, 0
    for mod in modules:
        nbs = instruction_notebooks(mod)
        if not nbs:
            continue  # not a content module
        md = QUIZZES / f"{mod.name.lower()}.md"
        sections, questions = quiz_stats(md)
        mod_date = git_last_date(nbs)
        quiz_date = git_last_date([md]) if md.exists() else None

        if questions == 0:
            status = "❌ needs questions"
            needs += 1
        elif mod_date and quiz_date and mod_date > quiz_date:
            status = "⚠️ stale — module changed since"
            stale += 1
        else:
            status = "✅ up to date"
            ok += 1

        rows.append({
            "module": mod.name,
            "have": "yes" if questions else "—",
            "sections": str(sections) if sections else "—",
            "questions": str(questions) if questions else "—",
            "quiz_date": quiz_date or "—",
            "mod_date": mod_date or "—",
            "status": status,
        })

    if check_only:
        for r in rows:
            if not r["status"].startswith("✅"):
                print(f"{r['module']}: {r['status']} "
                      f"(questions updated {r['quiz_date']}, module updated {r['mod_date']})")
        print(f"{ok} ok, {stale} stale, {needs} need questions")
        return 1 if (stale or needs) else 0

    today = subprocess.run(
        ["git", "-C", str(REPO), "log", "-1", "--format=%cs"],
        capture_output=True, text=True,
    ).stdout.strip()

    lines = [
        "# Practice Quiz Status",
        "",
        f"_Auto-generated by `quiz_site/quiz_status.py` (latest commit {today}). "
        "Do not hand-edit. Regenerate after editing quizzes or notebooks._",
        "",
        f"**Coverage:** {ok} up to date · {stale} stale · {needs} need questions "
        f"({len(rows)} content modules).",
        "",
        "| Module | Quiz? | Sections | Questions | Questions updated | Module updated | Status |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['module']} | {r['have']} | {r['sections']} | {r['questions']} "
            f"| {r['quiz_date']} | {r['mod_date']} | {r['status']} |"
        )
    lines += [
        "",
        "**Legend**",
        "- ✅ up to date — quiz exists and is at least as new as the module's instruction notebooks.",
        "- ⚠️ stale — an instruction notebook was committed more recently than the quiz; review the questions.",
        "- ❌ needs questions — no quiz Markdown for this module yet.",
        "",
        "_Staleness compares git commit dates of `quizzes/<module>.md` against the module's "
        "`NN_M_*.ipynb` instruction notebooks. `*_Exercises*` notebooks are excluded._",
        "",
    ]
    (QUIZZES / "STATUS.md").write_text("\n".join(lines))
    print(f"wrote quizzes/STATUS.md — {ok} ok, {stale} stale, {needs} need questions")
    return 0


if __name__ == "__main__":
    sys.exit(main(check_only="--check" in sys.argv[1:]))
